### PR TITLE
Force secure flag to true if sameSite=none - for delete methods

### PR DESCRIPTION
**Pull request by Yohandah**
this is the follow up of #89 , the delete methods weren't updated to default Lax

### CODE REVIEW

**Comment by brandontulsi** [comment]
@stevermeister please review for merge -- currently the library can't delete its own default cookies

**Comment by stevermeister** [comment]
@Yohandah @brandontulsi sorry guys, I missed this one

**Comment by stevermeister** [comment]
version 3.0.3 published

**Comment by brandontulsi** [comment]
@stevermeister thanks! 🎊 🎉

**Pull request merged**
