### PR TITLE
Upgrade to Angular 11

### LINKED ISSUE #117: Please add support for Angular 11
## Expected Behavior
Please add support for Angular 11

### PR DESCRIPTION
**Pull request by andreas-aeschlimann**
In order to make this package compatible with Angular 11, I suggest to make a new release:
- I have run `ng update @angular/cli @angular/core`.
- I also added the version number 11.0.0 and adjusted the peerDependencies in `package.json`.
- `npm run test` showed no errors after the upgrade.

Closes #117

### CODE REVIEW

**Comment by gwario** [comment]
I'd appreciate a merge and publish of the package, if the changes are okay.
Thanks!

**Comment by andreas-aeschlimann** [comment]
It should be okay now

**Comment by pavankjadda** [comment]
@andreas-aeschlimann any plans to merge this request?

**Comment by andreas-aeschlimann** [comment]
> @andreas-aeschlimann any plans to merge this request?

lol I am not an admin, I have no rights to merge here. :)

**Comment by pavankjadda** [comment]
@stevermeister  any plans to merge this request?

**Comment by stevermeister** [comment]
thank you @andreas-aeschlimann !

**Pull request merged**
