### PR TITLE
chore: upgrade to angular 12

### LINKED ISSUE #124: Please add support for Angular 12
## Expected Behavior
Angular 12 released today, please add support for it

### PR DESCRIPTION
**Pull request by pavankjadda**
This PR upgrades the library Angular version to 12.0.0 and closes #124

### CODE REVIEW

**Comment by pavankjadda** [comment]
@stevermeister Please review this and merge the request

**Comment by stevermeister** [comment]
@pavankjadda that was quick! thank you! 
no breaking changes?

**Comment by pavankjadda** [comment]
> @pavankjadda that was quick! thank you!
> no breaking changes?

Nope, I tested it on my machine and every works as expected. Moreover Angular 12 is an incremental change over 11

**Comment by pavankjadda** [comment]
@stevermeister and also updated methods documentation and did minor clean up. This is something I use in my project, I got a chance to upgrade my libraries, so I thought I might as well update this.

**Comment by pavankjadda** [comment]
@stevermeister Any update on this?

**Comment by stevermeister** [comment]
@pavankjadda yes, one more time thank you for your contribution! and sorry that I'm here not 24/7

**Comment by pavankjadda** [comment]
Sorry I was not trying to rush but just trying to find out I need to do anything else. And also I don't see any releases here https://github.com/stevermeister/ngx-cookie-service/releases, but I see latest version in NPM.

**Comment by stevermeister** [comment]
@pavankjadda I don't sync releases here on GitHub. Do you think it's usefull?

**Comment by pavankjadda** [comment]
@stevermeister You should. They are quite useful.

**Pull request merged**
