### PR TITLE
Adds cookies support for Angular Universal

### PR DESCRIPTION
**Pull request by pavankjadda**
In order to better understand this,  I went through [express.js](https://expressjs.com/en/starter/installing.html) tutorial. The `server.ts` has some basic `express.js` code. After debugging for few hours, I was able to identify the issue. Here is the summary

- When express server loads web page, it does have cookies in `request` object, but since our cookie service depends on `document` object we can't access them
- To fix this, first we need to provide `REQUEST` in providers. We can achieve this by modifying `server.ts` file
```
...............

  server.get('*', (req, res) => {
    res.render(indexHtml, {
      req, providers: [
        {provide: APP_BASE_HREF, useValue: req.baseUrl},
        {provide: 'REQUEST', useValue: (req)},
        {provide: 'RESPONSE', useValue: (res)}]
    });
  });
  return server;
};

...............
```
-  Then we need to inject `REQUEST` object in cookie service, which helps us to get cookies on server side through `REQUEST`
```
import {REQUEST} from '@nguniversal/express-engine/tokens';

@Injectable()
export class CookieService {
constructor(@Optional() @Inject(REQUEST) private request: Request) {
  }

```
- Then we need provide this in `AppServerModule`
```
@NgModule({
  imports: [
    AppModule,
    ServerModule,
  ],
  bootstrap: [AppComponent],
  providers: [CookieService]
})
export class AppServerModule {
}

```
- Finally, if the platform is server, we can get the cookies in the following way, otherwise we can use existing method
```
const result: RegExpExecArray = regExp.exec(this.isServer ? this.request?.headers.get('cookie') : this.document.cookie);
```

I checked this in my project and it works. Let me know your thoughts on this

### CODE REVIEW

**Comment by stevermeister** [comment]
@pavankjadda I've sent them a message - https://github.com/salemdar/ngx-cookie/issues/393

**Comment by stevermeister** [comment]
@pavankjadda let's finalize and merge this one? or still have any doubts?

**Comment by pavankjadda** [comment]
> @pavankjadda let's finalize and merge this one? or still have any doubts? 

When 	cookie expires, the website loads forever. I will test it further and let you know.

**Comment by stevermeister** [comment]
@pavankjadda we only proxy cookies from the request, right? we don't cache them so it should not be any issues with expiration time

**Comment by pavankjadda** [comment]
> @pavankjadda we only proxy cookies from the request, right? we don't cache them so it should not be any issues with expiration time 

Exactly. I will do final tests and merge the PR.

**Comment by pavankjadda** [comment]
> @pavankjadda we only proxy cookies from the request, right? we don't cache them so it should not be any issues with expiration time 

Can you give me access to NPM Repository? I couldn't publish beta version through Github actiona. My Npm id is [jpavanaryan](https://www.npmjs.com/~jpavanaryan)

**Comment by stevermeister** [comment]
@pavankjadda sure thing, added

**Comment by pavankjadda** [comment]
> @pavankjadda sure thing, added

Thanks.

**Comment by pavankjadda** [comment]
@stevermeister this is ready for review. We can merge this PR. Few things to note

- Treat this as foundation PR for SSR. Bug fixes and improvements can be added later
- I only added `get()` method as of right now, we can `getAll()` and other methods in future
- We still need to update docs
- I think we should announce this only when everything is ready and we are confident that everyone can use.

Let me know your thoughts

**Comment by stevermeister** [comment]
@pavankjadda 

agree. 
only I think we can add `getAll()` now, within this PR, if you don't see a lot of hidden complexity here

**Comment by pavankjadda** [comment]
Done. Updated `getAll()` as well.

**Comment by stevermeister** [comment]
Hi @pavankjadda,

could you please update me with the status of it? 
I thought we already agreed on everything and decided to merge it. 
I just found some time to return back to this and create a nice code example and also probably update some docs.

**Comment by johanchouquet** [comment]
Hi @pavankjadda and @pavankjadda ,

Would this PR be ported back on ngx-cookie-service v12 or only available for v13 ?
I'm indeed very much interested by this.

Thank you in advance for this!

**Comment by Spawnrad** [comment]
Hi,

I'm interested too. Any news about this merge?

Thanks <3

**Comment by pavankjadda** [comment]
> Hi @pavankjadda,
> 
> could you please update me with the status of it? I thought we already agreed on everything and decided to merge it. I just found some time to return back to this and create a nice code example and also probably update some docs.

I added `getAll()` method and merged the changes. I couldn't get time to update docs. I will do it soon.

**Comment by pavankjadda** [comment]
Looks like this PR was accidentally closed and the branch was deleted. Created new PR #199 with same changes

**Pull request closed without merging**
