### PR TITLE
feat(ssr): adds SSR support

### PR DESCRIPTION
**Pull request by pavankjadda**
In order to better understand this,  I went through [express.js](https://expressjs.com/en/starter/installing.html) tutorial. The `server.ts` has some basic `express.js` code. After debugging for few hours, I was able to identify the issue. Here is the summary

- When express server loads web page, it does have cookies in `request` object, but since our cookie service depends on `document` object we can't access them
- To fix this, first we need to provide `REQUEST` in providers. We can achieve this by modifying `server.ts` file
```
...............

  server.get('*', (req, res) => {
    res.render(indexHtml, {
      req, providers: [
        {provide: APP_BASE_HREF, useValue: req.baseUrl},
        {provide: 'REQUEST', useValue: (req)},
        {provide: 'RESPONSE', useValue: (res)}]
    });
  });
  return server;
};

...............
```
-  Then we need to inject `REQUEST` object in cookie service, which helps us to get cookies on server side through `REQUEST`
```
import {REQUEST} from '@nguniversal/express-engine/tokens';

@Injectable()
export class CookieService {
constructor(@Optional() @Inject(REQUEST) private request: Request) {
  }

```
- Then we need provide this in `AppServerModule`
```
@NgModule({
  imports: [
    AppModule,
    ServerModule,
  ],
  bootstrap: [AppComponent],
  providers: [CookieService]
})
export class AppServerModule {
}

```
- Finally, if the platform is server, we can get the cookies in the following way, otherwise we can use existing method
```
const result: RegExpExecArray = regExp.exec(this.isServer ? this.request?.headers.get('cookie') : this.document.cookie);
```

I checked this in my project and it works. Let me know your thoughts on this

### CODE REVIEW

**Review by stevermeister — APPROVED** [review]

**Comment by Spawnrad** [comment]
@stevermeister is it possible to have a code example to implement that please?

Thank you a lot both of you for this support <3

**Comment by pavankjadda** [comment]
> 

Yes, I am in the process of updating the docs.

**Comment by pavankjadda** [comment]
@Spawnrad you can try version `13.1.0` to test this. See the docs [here](https://github.com/stevermeister/ngx-cookie-service#server-side-rendering) and example [here](https://github.com/pavankjadda/angular-ssr-docker)

**Comment by Spawnrad** [comment]
Thank you a lot <3

**Pull request merged**
